// <auto-generated />
using CalculatonDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalculatonDAL.Migrations
{
    [DbContext(typeof(CalculationLogContext))]
    [Migration("20221215104240_calcinit")]
    partial class calcinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalculatonDAL.Models.CalculationItem", b =>
                {
                    b.Property<int>("CalculationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("calculation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalculationId"));

                    b.Property<int>("NumberOne")
                        .HasColumnType("integer")
                        .HasColumnName("number_one");

                    b.Property<int>("NumberTwo")
                        .HasColumnType("integer")
                        .HasColumnName("number_two");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_code");

                    b.Property<int>("Result_Value")
                        .HasColumnType("integer")
                        .HasColumnName("result_value");

                    b.HasKey("CalculationId");

                    b.ToTable("calcution_item");
                });
#pragma warning restore 612, 618
        }
    }
}
